### ISSUE TITLE
Error adding plugin - libCaptureCore.a" not found!

### ISSUE THREAD

**Issue by shekhartupe** [SocketMobile/capturebasic-cordova-ios#1]
I am going by instructions provided and facing error while adding plugin to my ionic cordova mobile applicaiton.

```
macbook-pro:xload ctupe$ cordova plugin add /Users/ctupe/workspace/capturebasic-cordova-ios 
Installing "com-socketmobile-capturebasic-cordova" for ios
Error during processing of action! Attempting to revert...
Failed to install 'com-socketmobile-capturebasic-cordova': CordovaError: Uh oh!
"/Users/ctupe/workspace/xsip/xload/plugins/com-socketmobile-capturebasic-cordova/src/ios/sdk/lib/libCaptureCore.a" not found!
    at copyFile (/Users/ctupe/workspace/xsip/xload/platforms/ios/cordova/lib/plugman/pluginHandlers.js:309:36)
    at copyNewFile (/Users/ctupe/workspace/xsip/xload/platforms/ios/cordova/lib/plugman/pluginHandlers.js:335:5)
    at installHelper (/Users/ctupe/workspace/xsip/xload/platforms/ios/cordova/lib/plugman/pluginHandlers.js:259:13)
    at install (/Users/ctupe/workspace/xsip/xload/platforms/ios/cordova/lib/plugman/pluginHandlers.js:34:13)
    at ActionStack.process (/Users/ctupe/workspace/xsip/xload/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/ctupe/workspace/xsip/xload/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:112:24)
    at PluginManager.addPlugin (/Users/ctupe/workspace/xsip/xload/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:142:21)
    at Api.addPlugin (/Users/ctupe/workspace/xsip/xload/platforms/ios/cordova/Api.js:254:10)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:561:10)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:344:28
Uh oh!
"/Users/ctupe/workspace/xsip/xload/plugins/com-socketmobile-capturebasic-cordova/src/ios/sdk/lib/libCaptureCore.a" not found!
macbook-pro:xload ctupe$ 

```

Please help.

**Comment by EricGlaenzer** [comment]
After running `updateCaptureSdk.sh`  as mentioned in the Readme you should end-up with a library (.a) under the `src/ios/sdk/lib/`.

The latest version of the Capture SDK for iOS have a different path for this library. I recommend you modify the plugin.xml locally and change the following lines to update the path of the library that should be located under `ios/sdk/lib/SKTCapture.xcframework` . Since Apple has changed the library format, the x86 processor version of the library is no longer packaged with the ARM processor versions of the library.
 
```
    <source-file src="src/ios/sdk/lib/libCaptureCore.a" framework="true"/>
    <source-file src="src/ios/sdk/lib/libCaptureServiceDirect.a" framework="true"/>
```

The other approach could be to use a version prior the new XCFramework format. You can see the history of the cocoapods-capture-obj-c repo.

We will update this plugin in the coming month.

**Comment by shekhartupe** [comment]
Thanks @EricGlaenzer, I went with second approach with version 1.2.53. Master does not have other dependencies per plugin.xml, unless all we need us libCapture.a.

**Comment by EricGlaenzer** [comment]
This should be resolved now with the latest version
